import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies';
import { Queue } from 'workbox-background-sync';

// Precache all of the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// Create a Queue for offline requests
const queue = new Queue('posts-offline', {
  maxRetentionTime: 24 * 60, // 24 hours
});

// Register routes for external CDN resources
registerRoute(
  new RegExp('https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css'),
  new CacheFirst({
    cacheName: 'bootstrap-cache',
  })
);

registerRoute(
  new RegExp('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'),
  new CacheFirst({
    cacheName: 'fontawesome-cache',
  })
);

// Verification token route
registerRoute(
  new RegExp('http://localhost:9090/api/auth/renew'),
  new NetworkFirst({
    cacheName: 'token-cache',
  })
);

// Events API route for GET requests
registerRoute(
  ({ url, request }) => {
    return url.href.includes('/api/events') && request.method === 'GET';
  },
  new NetworkFirst({
    cacheName: 'events-cache',
  })
);

// Intercept POST/PUT/DELETE to /api/events
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);
  
  // Only handle mutation requests to events API
  if (url.pathname.includes('/api/events') && ['POST', 'PUT', 'DELETE'].includes(request.method)) {
    const requestClone = request.clone();
    
    event.respondWith(
      fetch(request).catch(async (error) => {
        // Network failed, queue the request
        await queue.pushRequest({ request: requestClone });
        console.log('Request queued for background sync:', request.url);
        
        // Return a fake successful response so the app doesn't break
        return new Response(
          JSON.stringify({ 
            ok: true, 
            offline: true,
            message: 'Request saved for sync',
            data: { id: 'temp-' + Date.now() }
          }),
          { 
            status: 200,
            headers: { 'Content-Type': 'application/json' }
          }
        );
      })
    );
  }
});

// Force replay queue when online
self.addEventListener('message', async (event) => {
  if (event.data && event.data.type === 'REPLAY_QUEUE') {
    const entries = await queue.getAll();
    console.log('Replaying queue, entries:', entries.length);
    
    for (const entry of entries) {
      try {
        await fetch(entry.request.clone());
        await queue.shiftRequest();
        console.log('Request replayed successfully');
      } catch (error) {
        console.log('Replay failed, will retry later');
        break;
      }
    }
    
    // Notify clients to refresh
    const clients = await self.clients.matchAll();
    clients.forEach(client => {
      client.postMessage({ type: 'SYNC_COMPLETE' });
    });
  }
});
