import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';

// Precache all of the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// Register routes for external CDN resources
registerRoute(
  new RegExp('https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css'),
  new CacheFirst({
    cacheName: 'bootstrap-cache',
  })
);

registerRoute(
  new RegExp('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css'),
  new CacheFirst({
    cacheName: 'fontawesome-cache',
  })
);


// Verification token route
registerRoute(
  new RegExp('http://localhost:9090/api/auth/renew'),
  new NetworkFirst({
    cacheName: 'token-cache',
  })
);

// Events API route
registerRoute(
  new RegExp('http://localhost:9090/api/events'),
  new NetworkFirst({
    cacheName: 'events-cache',
  })
);